### ISSUE TITLE
Update UI and add splash for hacktoberfest 2021

### ISSUE THREAD

**Issue by AryamanGurjar** [dhruv1214/Quizz_App#5]
Hello sir,
I want to contribute to your repo for hactoberfest 2021
I want to add a splash screen and update its UI
 :-)
can you please send me an image to be used in splash screen on my main
aryamangurjar6@gmail.com

**Comment by dhruv1214** [comment]
You can use your own splash screen image. Make sure you will not do any un-regular activities with this repo then only i'll merge.

**Comment by AryamanGurjar** [comment]
Ok sir 😊

**Comment by dhruv1214** [comment]
Issue Resolved.
